---

unitClasses:
  - id: barracks_ap
    name: structure_name_barracks
    aiPriority: 4.0
    verbs:
      - recruit_ap
    battleUnitCount: 1
    isStructure: true
    garrisonUnit: garrison
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: true
    damageMultiplier: 1
    movement: land_building
    income: 0
    cost: 500
    recruitTags: [type.ground.light, type.ground.heavy]
    regeneration: 10
    tags:
      - structure
    sightRange: 1
      
units:
  - class: barracks_ap
    faction: neutral
    name: structure_name_barracks
    mapAnimation: structures/barracks
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.65, 0.35]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/barracks.png
    grabPos: [11, 7]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/barracks/barracks_background_full
      farBackground: barracks_background_full_background_2
      nearBackground: barracks_background_full_background_1
      foreground: barracks_background_full_foreground
      keeperPosition: [74, 85]
      leftBannerOffset: [2, 0]
      rightBannerOffset: [3, 1]
...