---

unitClasses:
  - id: port_ap
    name: structure_name_port
    aiPriority: 4.0
    verbs:
      - recruit_ap
    battleUnitCount: 1
    isStructure: true
    garrisonUnit: garrison
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: true
    canBeCursed: false
    isNeutraliseable: true
    damageMultiplier: 1
    movement: river_sea_building
    income: 0
    cost: 500
    recruitTags: [type.sea.light, type.sea.medium, type.sea.heavy, type.amphibious.light, type.amphibious.heavy]
    regeneration: 10
    tags:
      - structure
    sightRange: 1
      
units:
  - class: port_ap
    faction: neutral
    name: structure_name_port
    mapAnimation: structures/port
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.8, 0.8]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/port.png
    grabPos: [14, 5]
    sounds:
      hit: hitWood
      hitMap: hitWood
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/port/port_background_full
      farBackground: port_background_full_background_2
      nearBackground: port_background_full_background_1
      foreground: port_background_full_foreground
      keeperPosition: [66, 98]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [-7, 0]

...