---

unitClasses:
  - id: tower_ap
    name: structure_name_tower
    aiPriority: 4.0
    verbs:
      - recruit_ap
    battleUnitCount: 1
    garrisonUnit: garrison
    isStructure: true
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: true
    damageMultiplier: 1
    movement: land_building
    income: 0
    cost: 500
    recruitTags: [type.air]
    regeneration: 10
    tags:
      - structure
    sightRange: 1
      
units:
  - class: tower_ap
    faction: neutral
    name: structure_name_tower
    mapAnimation: structures/tower
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.8, 0.8]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/tower.png
    grabPos: [14, 4]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/tower/tower_background_full
      farBackground: tower_background_full_background_2
      nearBackground: tower_background_full_background_1
      foreground: tower_background_full_foreground
      keeperPosition: [72, 75]
      leftBannerOffset: [0, 0]
      rightBannerOffset: [0, 0]

...