---

triggerActions:
  - id: ap_item_check
  - id: ap_victory

  - id: ap_count_item
    parameters:
        - type: integer
        - type: counter

  - id: ap_location_send
    parameters:
      - type: integer

  - id: ap_income_boost
    parameters:
      - type: player_star

  - id: ap_co_defense_boost

  - id: unit_random_teleport
    parameters:
      - type: unit_class_star
      - type: player_neutral_star
      - type: location_star
      - type: location_star
      - type: boolean

...
