---

triggerActions:
  - id: ap_victory
    parameters:
      - type: string

  - id: ap_count_item
    parameters:
        - type: integer
        - type: counter

  - id: ap_location_send
    parameters:
      - type: integer

  - id: ap_prng_seed_num
    parameters:
      - type: integer

  - id: location_unit_random_teleport
    parameters:
      - type: location_star
      - type: unit_class_star
      - type: player_neutral_star
      - type: location_star

  - id: unit_random_teleport
    parameters:
      - type: unit_class_star
      - type: player_neutral_star
      - type: location_star
      - type: location_star
      - type: boolean

  - id: ap_random
    parameters:
      - type: counter
      - type: integer
      - type: integer

  - id: ap_spawn_unit
    parameters:
      - type: unit_class
      - type: location
      - type: player_neutral
      - type: boolean
      - type: boolean
      - type: integer
      - type: boolean
      - type: skin_colour
      - type: facing

  - id: ap_export
    parameters:
      - type: integer
      - type: string
      - type: string
      - type: string
      - type: string
      - type: string
      - type: string
  - id: ap_import
    parameters:
      - type: integer
...
